### ISSUE TITLE
[Super AI] Implement DeepSpeed to optimizer experiment

### ISSUE THREAD

**Issue by pitikorn32** [OpenThaiGPT/openthaigpt-pretraining#121]
Description:
Deepspeed is a technique to shard model gradients and optimizer state across GPUs to reduce model memory consumption. Please add DeepSpeed Zero Stage 1,2 to the optimizer experiment and see if it conflicts with Lion/8 Bit Adam.

Instructions:
- Add DeepSpeed as an option to select
- Add 1 Bit Adam

Deliverables:
- PR
- Test on Huawei Cloud

**Comment by pitikorn32** [comment]
In progress, I do it in colab via this link but found the error...
try to fix it
colab: [link](https://colab.research.google.com/drive/1_zP3RcyPBdfUx6Ae6dKA84KjbtShECI-?usp=sharing)

**Comment by pitikorn32** [comment]
ref:
- https://www.deepspeed.ai/getting-started/
- https://deepspeed.readthedocs.io/en/latest/initialize.html#deepspeed.initialize
- https://github.com/stas00/porting/blob/master/transformers/deepspeed/DeepSpeed_on_colab_CLI.ipynb
- https://github.com/microsoft/DeepSpeed/issues/2029

**Comment by pitikorn32** [comment]
my modified code
```python
self.opt = optim.AdamW(
                params=model.parameters(),
                lr=lr,
                weight_decay=weight_decay,
                betas=(0.9, 0.95),
                fused=True,
            )

            ds_config = {
                "train_micro_batch_size_per_gpu": batch_size,
                "fp16": {
                    "enabled": True
                },
                "zero_optimization": {
                    "stage": 1,
                    "offload_optimizer": {
                        "device": "cpu"
                    }
                },
                "zero_force_ds_cpu_optimizer": False
            }

            self.model, _, _, _ = deepspeed.initialize(
                                                        model=model,
                                                        optimizer=self.opt,
                                                        model_parameters=model.parameters(),
                                                        config = ds_config,
                                                        # config_params="./ds_config.json"
                                                        )
```

and found this error

```
[2023-05-22 19:01:32,200] [INFO] [utils.py:785:see_memory_usage] Before initializing optimizer states
[2023-05-22 19:01:32,200] [INFO] [utils.py:786:see_memory_usage] MA 0.32 GB         Max_MA 0.32 GB         CA 0.32 GB         Max_CA 0 GB 
[2023-05-22 19:01:32,200] [INFO] [utils.py:793:see_memory_usage] CPU Virtual Memory:  used = 29.41 GB, percent = 5.8%
Traceback (most recent call last):
  File "/lustrefs/disk/home/pkhlaisa/Petanque/test_deepspeed/main.py", line 340, in <module>
    trainer = Trainer(
  File "/lustrefs/disk/home/pkhlaisa/Petanque/test_deepspeed/main.py", line 231, in __init__
    self.model, _, _, _ = deepspeed.initialize(
  File "/home/pkhlaisa/.conda/envs/pytorch2.0/lib/python3.10/site-packages/deepspeed/__init__.py", line 165, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/pkhlaisa/.conda/envs/pytorch2.0/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 308, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/pkhlaisa/.conda/envs/pytorch2.0/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1173, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/pkhlaisa/.conda/envs/pytorch2.0/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1408, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/home/pkhlaisa/.conda/envs/pytorch2.0/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 485, in __init__
    self.initialize_optimizer_states()
  File "/home/pkhlaisa/.conda/envs/pytorch2.0/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 620, in initialize_optimizer_states
    self.optimizer.step()
  File "/home/pkhlaisa/.conda/envs/pytorch2.0/lib/python3.10/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/home/pkhlaisa/.conda/envs/pytorch2.0/lib/python3.10/site-packages/torch/optim/optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/pkhlaisa/.conda/envs/pytorch2.0/lib/python3.10/site-packages/torch/optim/adamw.py", line 173, in step
    adamw(
  File "/home/pkhlaisa/.conda/envs/pytorch2.0/lib/python3.10/site-packages/torch/optim/adamw.py", line 323, in adamw
    func(
  File "/home/pkhlaisa/.conda/envs/pytorch2.0/lib/python3.10/site-packages/torch/optim/adamw.py", line 616, in _fused_adamw
    torch._fused_adamw_(
NotImplementedError: Could not run 'aten::_fused_adamw_' with arguments from the 'CPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::_fused_adamw_' is only available for these backends: [CUDA, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].

CUDA: registered at aten/src/ATen/RegisterCUDA.cpp:44025 [kernel]
BackendSelect: fallthrough registered at ../aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:144 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at ../aten/src/ATen/functorch/DynamicLayer.cpp:491 [backend fallback]
Functionalize: registered at aten/src/ATen/RegisterFunctionalization_3.cpp:24170 [kernel]
Named: registered at ../aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ../aten/src/ATen/ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at ../aten/src/ATen/native/NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at ../aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:63 [backend fallback]
AutogradOther: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradCPU: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradCUDA: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradHIP: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradXLA: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradMPS: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradIPU: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradXPU: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradHPU: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradVE: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradLazy: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradMeta: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradMTIA: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradPrivateUse1: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradPrivateUse2: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradPrivateUse3: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
AutogradNestedTensor: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:15868 [autograd kernel]
Tracer: registered at ../torch/csrc/autograd/generated/TraceType_1.cpp:15852 [kernel]
AutocastCPU: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:344 [backend fallback]
AutocastCUDA: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:211 [backend fallback]
FuncTorchBatched: registered at ../aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:710 [backend fallback]
FuncTorchVmapMode: fallthrough registered at ../aten/src/ATen/functorch/VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at ../aten/src/ATen/LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at ../aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at ../aten/src/ATen/functorch/TensorWrapper.cpp:219 [backend fallback]
PythonTLSSnapshot: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:152 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ../aten/src/ATen/functorch/DynamicLayer.cpp:487 [backend fallback]
PythonDispatcher: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:148 [backend fallback]
```
